version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
    ports:
      - 5432:5432
    command: postgres -N 1000
# sqlx database create --database-url postgres://postgres:postgres@localhost:5432/newsletter
# sqlx migrate run --database-url postgres://postgres:postgres@localhost:5432/newsletter
